name: nocotine
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0


  cupertino_icons: ^1.0.2
  flutter_datetime_picker: ^1.5.1
  date_time_picker: ^2.1.0
  flutter_datetime_picker_bdaya: ^2.0.0
  flutter_spinbox: ^0.8.0
  rflutter_alert: ^2.0.4
  expansion_widget: ^0.0.3
  awesome_dialog: ^2.1.2
  nice_buttons: ^0.0.2
  neon_circular_timer: ^0.0.7
  shared_preferences: ^2.0.13
  comment_box: ^0.0.17
  flutter_rating_bar: ^4.0.0
  http: ^0.13.4
  permission_handler: ^9.2.0
  image_picker: ^0.8.4+10
  url_launcher: ^6.0.20
  flutter_svg: ^1.0.3
  video_player: ^2.3.0
  flick_video_player: ^0.3.1
  flutter_chat_bubble: ^2.0.0
  animated_icon_button: ^1.0.2
  google_nav_bar: ^5.0.6
  keyboard_attachable: ^2.1.0
  full_screen_image_null_safe: ^2.0.0
  syncfusion_flutter_pdfviewer: ^20.1.47-beta
  firebase_core: ^1.14.0
  firebase_messaging: ^11.2.12
  another_flushbar: ^1.10.28
  badges: ^2.0.2
  dropdown_search: ^2.0.1
  dio: ^4.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
  fonts:
    - family: Baloo 2
      fonts:
        - asset: assets\fonts\Baloo2-Regular.ttf
          weight: 300
        - asset: assets\fonts\Baloo2-Regular.ttf
          weight: 400
        - asset: assets\fonts\Baloo2-Medium.ttf
          weight: 500
        - asset: assets\fonts\Baloo2-Bold.ttf
          weight: 700
        - asset: assets\fonts\Baloo2-ExtraBold.ttf
          weight: 800


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
